import {
    AccountBookOutlined,
    AimOutlined,
    ApartmentOutlined,
    ArrowRightOutlined,
    CodeSandboxOutlined,
    DashboardOutlined,
    InsertRowAboveOutlined,
    LineChartOutlined,
    LockOutlined,
    MobileOutlined,
    SmileOutlined,
    TeamOutlined,
    UserOutlined,
} from "@ant-design/icons";

export default {
    arrowRight: <ArrowRightOutlined />,
    userIcon: <UserOutlined />,
    mobileIcon: <MobileOutlined />,
    smCodeIcon: <CodeSandboxOutlined />,
    passwordIcon: <LockOutlined />,
    department: <ApartmentOutlined />,
    level: <AimOutlined />,
    assessment: <InsertRowAboveOutlined />,
    reward: <SmileOutlined />,
    salary: <AccountBookOutlined />,
    dashboard: <DashboardOutlined />,
    attendance: <LineChartOutlined />,
    team: <TeamOutlined />,
};
