import {
    ArrowRightOutlined,
    MobileOutlined,
    UserOutlined,
    CodeSandboxOutlined,
    LockOutlined,
    ApartmentOutlined,
    AimOutlined,
    InsertRowAboveOutlined,
    SmileOutlined,
    AccountBookOutlined,
    DashboardOutlined,
    LineChartOutlined,
    TeamOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    DatabaseOutlined,
    WalletOutlined,
    BarChartOutlined,
    FileAddOutlined,
    DeleteOutlined,
    CaretLeftOutlined,
    CaretRightOutlined,
    ReloadOutlined,
    FormOutlined,
    CopyOutlined,
    ApiOutlined,
    CloseCircleOutlined,
    ExclamationCircleOutlined
} from '@ant-design/icons';

export default {
    arrowRight: <ArrowRightOutlined />,
    userIcon: <UserOutlined />,
    mobileIcon: <MobileOutlined />,
    smCodeIcon: <CodeSandboxOutlined />,
    passwordIcon: <LockOutlined />,
    department: <ApartmentOutlined />,
    level: <AimOutlined />,
    assessment: <InsertRowAboveOutlined />,
    reward: <SmileOutlined />,
    salary: <AccountBookOutlined />,
    dashboard: <DashboardOutlined />,
    attendance: <LineChartOutlined />,
    team: <TeamOutlined />,
    leftArrow: <MenuFoldOutlined />,
    rightArrow: <MenuUnfoldOutlined />,
    rewardAndPunishment: <DatabaseOutlined />,
    signOut: <WalletOutlined />,
    'bar-chart': <BarChartOutlined />,
    add: <FileAddOutlined />,
    api: <ApiOutlined />,
    del: <DeleteOutlined />,
    close: <CloseCircleOutlined />,
    left: <CaretLeftOutlined />,
    reload: <ReloadOutlined />,
    right: <CaretRightOutlined />,
    detail: <FormOutlined />,
    copy: <CopyOutlined />,
    tip: <ExclamationCircleOutlined />
};
