import {
    AccountBookOutlined,
    AimOutlined,
    ApartmentOutlined,
    ArrowRightOutlined,
    BarChartOutlined,
    CodeSandboxOutlined,
    DashboardOutlined,
    DatabaseOutlined,
    InsertRowAboveOutlined,
    LineChartOutlined,
    LockOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    MobileOutlined,
    SmileOutlined,
    TeamOutlined,
    UserOutlined,
    WalletOutlined,
} from "@ant-design/icons";

export default {
    arrowRight: <ArrowRightOutlined />,
    userIcon: <UserOutlined />,
    mobileIcon: <MobileOutlined />,
    smCodeIcon: <CodeSandboxOutlined />,
    passwordIcon: <LockOutlined />,
    department: <ApartmentOutlined />,
    level: <AimOutlined />,
    assessment: <InsertRowAboveOutlined />,
    reward: <SmileOutlined />,
    salary: <AccountBookOutlined />,
    dashboard: <DashboardOutlined />,
    attendance: <LineChartOutlined />,
    team: <TeamOutlined />,
    leftArrow: <MenuFoldOutlined />,
    rightArrow: <MenuUnfoldOutlined />,
    rewardAndPunishment: <DatabaseOutlined />,
    signOut: <WalletOutlined />,
    "bar-chart": <BarChartOutlined />,
};
